# Generated by Django 2.1.3 on 2018-11-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='ayes',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='votes',
            name='nays',
            field=models.IntegerField(blank=True),
        ),
    ]
