# Generated by Django 2.1.3 on 2018-11-25 05:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_auto_20181125_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='subject',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='votes',
            name='vote_taken',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
